// Northstar v1 - synthetic seed data used to populate the SQLite database on first run.
import type { CourseInput, Goal } from "./types";

export const CTO_GOAL_ID = "become-a-cto";

export const INITIAL_GOALS: Goal[] = [{ id: CTO_GOAL_ID, name: "Become a CTO" }];

export const FDE_GOAL_ID = "become-a-fde";

export const FDE_GOAL: Goal = { id: FDE_GOAL_ID, name: "Become a FDE" };

// Sources researched via web search (Sept 2026): Palantir's original "Forward
// Deployed Engineer" role, the Awesome-FDE-Roadmap community roadmap, and
// coverage from Exponent, Salesforce, GeeksforGeeks, and DeepLearning.AI.
export const FDE_COURSES: CourseInput[] = [
  {
    goalId: FDE_GOAL_ID,
    category: "FDE Fundamentals",
    name: "Awesome FDE Roadmap",
    platform: "GitHub (pierpaolo28)",
    link: "https://github.com/pierpaolo28/Awesome-FDE-Roadmap",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "2h",
    notes:
      'Community roadmap to becoming a Forward Deployed Engineer, covering AI agents, enterprise data architecture, and strategic consulting - inspired by the "Delta" role at Palantir, OpenAI, and Scale AI.',
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "FDE Fundamentals",
    name: "What Is a Forward Deployed Engineer? Complete Guide",
    platform: "Exponent (Aced)",
    link: "https://www.tryexponent.com/blog/what-is-a-forward-deployed-engineer",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "1h",
    notes:
      "Overview of the role, its origin at Palantir, day-to-day responsibilities, and how it differs from a typical software engineering or solutions architect job.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Data & Analytics Engineering",
    name: "dbt Fundamentals",
    platform: "dbt Learn",
    link: "https://learn.getdbt.com/courses/dbt-fundamentals",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "6h",
    notes:
      "Hands-on course on modeling, testing, documentation, and deployment with dbt - core to the data-pipeline work FDEs do on customer sites.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Data & Analytics Engineering",
    name: "Advanced SQL: Window Functions",
    platform: "Mode",
    link: "https://mode.com/blog/most-popular-window-functions-and-how-to-use-them/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "3h",
    notes:
      "Window functions and CTEs came up repeatedly as a named FDE competency - this covers the five most-used window functions with worked examples.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Systems & Architecture",
    name: "The System Design Primer",
    platform: "GitHub (donnemartin)",
    link: "https://github.com/donnemartin/system-design-primer",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "15h",
    notes:
      "Large-scale systems design fundamentals - scalability, data pipelines, and tradeoffs FDEs need when standing up custom apps inside a customer's infrastructure.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Applied AI Engineering",
    name: "AI Agents in LangGraph",
    platform: "DeepLearning.AI",
    link: "https://www.deeplearning.ai/courses/ai-agents-in-langgraph",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "2h",
    notes:
      "Build agentic AI workflows with LangGraph, including persistence and human-in-the-loop patterns - directly applicable to embedding custom AI solutions with customers.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Applied AI Engineering",
    name: "Functions, Tools and Agents with LangChain",
    platform: "DeepLearning.AI",
    link: "https://www.deeplearning.ai/courses/functions-tools-agents-langchain",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "1h 30m",
    notes:
      "Function calling and tool-use patterns for wiring LLMs into real customer systems, taught by LangChain's founder and Andrew Ng.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Client & Communication Skills",
    name: "Technical Writing One",
    platform: "Google for Developers",
    link: "https://developers.google.com/tech-writing/one",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "4h",
    notes:
      "Critical basics of clear technical writing - FDEs constantly document integrations and explain technical tradeoffs to non-technical stakeholders.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Client & Communication Skills",
    name: "Forward Deployed Engineer: 5 Skills for This New Role",
    platform: "Salesforce Blog",
    link: "https://www.salesforce.com/blog/forward-deployed-engineer/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "1h",
    notes:
      "Breaks down the communication and business-acumen side of the role - engaging execs and business stakeholders without leaning on jargon.",
    userNote: "",
  },
  {
    goalId: FDE_GOAL_ID,
    category: "Career Roadmap",
    name: "Forward Deployed Engineer: Role, Skills, Salary & Career Roadmap",
    platform: "GeeksforGeeks",
    link: "https://www.geeksforgeeks.org/blogs/forward-deployed-engineer-role-skills-salary-roadmap/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "1h 30m",
    notes:
      "Structured overview of the FDE career path end to end - useful as a checkpoint to revisit once the other topics here are underway.",
    userNote: "",
  },
];

export const INITIAL_COURSES: CourseInput[] = [
  {
    goalId: CTO_GOAL_ID,
    category: "Technical Leadership",
    name: "Engineering Leadership: From Manager to Director",
    platform: "LinkedIn Learning",
    link: "https://www.linkedin.com/learning/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2026-02-10",
    timeToComplete: "4h 30m",
    notes: "Good framework for scaling a team past ~30 engineers without losing technical depth.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Technical Leadership",
    name: "The Staff Engineer's Path",
    platform: "O'Reilly (Book)",
    link: "https://www.oreilly.com/",
    status: "In Progress",
    progress: 40,
    lastCompleted: null,
    timeToComplete: "8h",
    notes: "On the chapter about influence without authority. Useful for the IC-to-exec bridge.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Technical Leadership",
    name: "Architecting for Scale",
    platform: "Coursera",
    link: "https://www.coursera.org/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "12h",
    notes: "Queued after finishing the distributed systems book below.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Cloud & Systems Architecture",
    name: "AWS Certified Solutions Architect - Professional",
    platform: "AWS Training",
    link: "https://aws.amazon.com/certification/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2025-11-02",
    timeToComplete: "40h",
    notes:
      "Renewal due 2028. Biggest single time investment so far, worth it for credibility with infra teams.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Cloud & Systems Architecture",
    name: "Designing Data-Intensive Applications",
    platform: "O'Reilly (Book)",
    link: "https://www.oreilly.com/",
    status: "In Progress",
    progress: 55,
    lastCompleted: null,
    timeToComplete: "20h",
    notes:
      "Slow read but foundational - want to be able to challenge architecture proposals directly.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Cloud & Systems Architecture",
    name: "Kubernetes for Platform Engineers",
    platform: "Udemy",
    link: "https://www.udemy.com/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2026-04-18",
    timeToComplete: "10h",
    notes: "Enough to have an informed opinion in platform reviews, not enough to run prod myself.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Cloud & Systems Architecture",
    name: "System Design Interview Deep Dive",
    platform: "Educative",
    link: "https://www.educative.io/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "15h",
    notes:
      'Useful less for interviews, more for calibrating what "good" looks like when hiring architects.',
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Business & Finance",
    name: "Finance for Non-Financial Managers",
    platform: "Coursera",
    link: "https://www.coursera.org/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2026-01-05",
    timeToComplete: "6h",
    notes: "Cleared up how R&D spend actually shows up on the income statement.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Business & Finance",
    name: "Reading a P&L Like a CFO",
    platform: "LinkedIn Learning",
    link: "https://www.linkedin.com/learning/",
    status: "In Progress",
    progress: 65,
    lastCompleted: null,
    timeToComplete: "3h",
    notes: "Short course, doing it alongside real board deck reviews.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Business & Finance",
    name: "Startup Financial Modeling",
    platform: "Udemy",
    link: "https://www.udemy.com/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "5h",
    notes:
      "Want to be able to build a headcount-vs-runway model without leaning on finance for every draft.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "People Management",
    name: "Radical Candor",
    platform: "Book",
    link: "https://www.radicalcandor.com/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2026-03-22",
    timeToComplete: "6h",
    notes: 'Reference this constantly in 1:1s now - especially the "ruinous empathy" trap.',
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "People Management",
    name: "Coaching Skills for Managers",
    platform: "Coursera",
    link: "https://www.coursera.org/",
    status: "In Progress",
    progress: 30,
    lastCompleted: null,
    timeToComplete: "5h",
    notes: "Practicing the GROW model in skip-levels this quarter.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "People Management",
    name: "Building High-Performing Engineering Cultures",
    platform: "Conference Talk Series",
    link: "https://www.youtube.com/",
    status: "Not Started",
    progress: 0,
    lastCompleted: null,
    timeToComplete: "4h",
    notes: "Curated playlist from LeadDev - saved for after the coaching course.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Strategy & Innovation",
    name: "The CTO Playbook",
    platform: "Book",
    link: "https://www.amazon.com/",
    status: "Completed",
    progress: 100,
    lastCompleted: "2026-06-30",
    timeToComplete: "7h",
    notes:
      "Best single overview of the role split (tech strategy vs. delivery vs. people) I've read so far.",
    userNote: "",
  },
  {
    goalId: CTO_GOAL_ID,
    category: "Strategy & Innovation",
    name: "Technology Strategy for the C-Suite",
    platform: "Wharton Executive Education",
    link: "https://online.wharton.upenn.edu/",
    status: "In Progress",
    progress: 70,
    lastCompleted: null,
    timeToComplete: "18h",
    notes:
      "Executive cohort course - case studies are directly relevant to our build-vs-buy debates.",
    userNote: "",
  },
];
